DROP TABLE IF EXISTS jelo;
DROP TABLE IF EXISTS restoran;

create table restoran (id bigint generated by default as identity, adresa varchar(255), naziv varchar(255), ocena float(53) not null, telefon varchar(255), primary key (id));
create table jelo (id bigint generated by default as identity, cena float(53) not null, naziv varchar(255), opis varchar(255), id_restorana bigint not null, primary key (id));

alter table if exists jelo add constraint FK_jelo_restoran foreign key (id_restorana) references restoran;

insert into restoran (id, adresa, naziv, ocena, telefon) values (1001, 'Adresa restorana 1', 'Restoran 1', 9, '061234567');
insert into restoran (id, adresa, naziv, ocena, telefon) values (1002, 'Adresa restorana 2', 'Restoran 2', 10, '061234567');
insert into restoran (id, adresa, naziv, ocena, telefon) values (1003, 'Adresa restorana 3', 'Restoran 3', 6, '061234567');
insert into restoran (id, adresa, naziv, ocena, telefon) values (1004, 'Adresa restorana 4', 'Restoran 4', 8, '061234567');
insert into restoran (id, adresa, naziv, ocena, telefon) values (1005, 'Adresa restorana 5', 'Restoran 5', 5, '061234567');
insert into restoran (id, adresa, naziv, ocena, telefon) values (1006, 'Adresa restorana 6', 'Restoran 6', 6, '061234567');
insert into restoran (id, adresa, naziv, ocena, telefon) values (1007, 'Adresa restorana 7', 'Restoran 7', 7, '061234567');
insert into jelo (id, cena, naziv, opis, id_restorana) values (default, 500, 'Naziv jela 1', 'Opis jela 1', 1001);